- id: doi:10.1158/0008-5472.can-22-0656
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/82/15/2/m_canres_82_15_cover.png

- id: doi:10.1016/j.ijrobp.2024.09.006
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0360301624X00164-cov200h.gif

- id: doi:10.1186/s13287-024-03734-z
  image: https://media.springernature.com/w316/springer-static/cover-hires/journal/13287?as=webp

- id: doi:10.1172/jci.insight.181330
  image: images/jciinsightjeb.jpg

- id: doi:10.3389/facou.2025.1616297
  image: images/michelle2025.png