- id: doi:10.1158/0008-5472.can-22-0656
  image: https://aacr.silverchair-cdn.com/aacr/content_public/journal/cancerres/issue/82/15/2/m_canres_82_15_cover.png?Expires=1712534177&Signature=PPO2tJ7xS4xzDMN4lnC1-5wrEpG01J1wW5X09DsMiNwZYs5mOngadVtVtyplcxKi~QasUlD0JGVoCnFtHqR2DZZD9zcZL49ZgjJutI7hE0HWm2wYjhi~QF93SUm9UKbirJx4ZYQumV2eY5ZpIzbkgmVAXhNHUZ~bmRXxBp4QZFQ4tA19REePGRRuiNKpGTUYwdZ71DG8f5NThQksSwR9IPLnNS64tjycIjMQVK6X5doQV0Fv9SfAhatXHm-XITHj-KB9jvEQwgYou22pXZPqo3hr7V1tSKc4w9VH0G3ESycQoKYXguwx~7hafBIX4RyL7h-VxAaXkpKrL-WRsi6Wtg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1016/j.ijrobp.2024.09.006
  image: https://www.redjournal.org/cms/asset/84b43ee8-be65-4f72-acfc-8f0faaa242c3/cov200h.gif

- id: doi:10.1186/s13287-024-03734-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13287-024-03734-z/MediaObjects/13287_2024_3734_Fig5a_HTML.png?as=webp

  id: doi:10.1172/jci.insight.181330
  image: https://df6sxcketz7bb.cloudfront.net/volumes/9/21/9-21-cover.jpg

  id: http:https://www.frontiersin.org/journals/acoustics/articles/10.3389/facou.2025.1616297/abstract
  image: 